#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

SCRIPTS=(
    "${REPO_ROOT}/install.sh"
    "${REPO_ROOT}/1-capture_config/apply_camera_config.sh"
    "${REPO_ROOT}/1-capture_config/antcam"
    "${REPO_ROOT}/1-capture_config/antcam_focus_autofocus.sh"
    "${REPO_ROOT}/3-recording_scripts/video.sh"
    "${REPO_ROOT}/3-recording_scripts/photos.sh"
    "${REPO_ROOT}/4-upload/upload_worker.sh"
)

echo "[static-checks] Running bash syntax checks"
for script in "${SCRIPTS[@]}"; do
    bash -n "$script"
    echo "[static-checks] OK syntax: ${script}"
done

echo "[static-checks] Checking camera profile assets"
test -f "${REPO_ROOT}/1-capture_config/profiles/auto.conf"
test -f "${REPO_ROOT}/1-capture_config/profiles/imx708.conf"
test -f "${REPO_ROOT}/1-capture_config/profiles/owlcam.conf"
grep -q 'camera_auto_detect=1' "${REPO_ROOT}/1-capture_config/profiles/auto.conf"
grep -q 'dtoverlay=imx708' "${REPO_ROOT}/1-capture_config/profiles/imx708.conf"
grep -q 'dtoverlay=ov64a40' "${REPO_ROOT}/1-capture_config/profiles/owlcam.conf"
echo "[static-checks] OK camera profiles"

echo "[static-checks] Checking antcam command surface"
grep -q 'sudo antcam list' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'sudo antcam cam report' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'sudo antcam show <profile>' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'sudo antcam apply <profile>' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'antcam start <recording-script-name>' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'antcam start photos' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'antcam stop' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'antcam focus check' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'antcam focus set <lens-position|auto>' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'antcam fps set <value>' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'antcam length set <duration>' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'antcam segment set <duration>' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'antcam loop set <duration|none|0>' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'antcam upload set profile <field|cloud|local>' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'antcam upload set retention <protect|rolling>' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'antcam upload report queue' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'antcam upload report targets' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'antcam upload pause' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'antcam upload resume' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'antcam upload reload' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'antcam upload prune --older-than <duration> \[--dry-run\]' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'antcam focus report' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'antcam fps report' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'antcam length report' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'antcam segment report' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'antcam loop report' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'usage: antcam cam report' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'report_camera_make_model' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'camera_make_model_for_profile' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'Raspberry Pi Camera Module 3 (Sony IMX708)' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'Auto Detect: Raspberry Pi Camera Module 3 NoIR' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'publish_recording_event' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'recording_start' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'recording_end' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'recording_stop' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'encrypt=True' "${REPO_ROOT}/1-capture_config/antcam"
! grep -q -- '--no-encrypt' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'write_script_failure_diagnostic' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'diagnostics/recordings' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'resolve_focus_script_path' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'start_focus_check' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'drop_focus_photo_to_diagnostics' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'focus-result-lens-position-' "${REPO_ROOT}/1-capture_config/antcam"
grep -q '__T-' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'resolve_focus_hostname_for_filename' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'resolve_recording_script_path' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'resolve_fps_value_file_for_home' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'read_fps_setting_for_home' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'set_fps_value' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'resolve_length_value_file_for_home' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'resolve_segment_value_file_for_home' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'resolve_loop_value_file_for_home' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'resolve_recording_state_file_for_home' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'resolve_upload_profile_file_for_home' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'resolve_upload_queue_db_for_home' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'read_upload_service_env_value' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'read_upload_effective_rclone_remote_for_home' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'duration_to_milliseconds' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'normalize_loop_setting_value' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'set_upload_profile_value' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'set_upload_retention_value' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'report_upload_queue' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'report_upload_targets' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'reload_upload_worker_service' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'prune_uploaded_files' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'set_length_value' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'set_segment_value' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'set_loop_value' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'read_length_setting_for_home' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'read_segment_setting_for_home' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'read_loop_setting_for_home' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'report_loop_value' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'stop_recording' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'signal_pid_and_children' "${REPO_ROOT}/1-capture_config/antcam"
grep -q "stopping recording script '" "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'recording-active-state.env' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'recording-loop.txt' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'antcam_focus_autofocus.sh' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'recording-scripts' "${REPO_ROOT}/1-capture_config/antcam"
grep -q 'remove_conflicting_camera_lines' "${REPO_ROOT}/1-capture_config/antcam"
echo "[static-checks] OK antcam checks"

echo "[static-checks] Checking focus helper script"
test -f "${REPO_ROOT}/1-capture_config/antcam_focus_autofocus.sh"
grep -q 'autofocus-mode auto' "${REPO_ROOT}/1-capture_config/antcam_focus_autofocus.sh"
grep -q 'autofocus-on-capture' "${REPO_ROOT}/1-capture_config/antcam_focus_autofocus.sh"
grep -q 'LensPosition=' "${REPO_ROOT}/1-capture_config/antcam_focus_autofocus.sh"
grep -q 'FOCUS_IMAGE_PATH=' "${REPO_ROOT}/1-capture_config/antcam_focus_autofocus.sh"
grep -q 'rpicam-vid --lens-position' "${REPO_ROOT}/1-capture_config/antcam_focus_autofocus.sh"
echo "[static-checks] OK focus helper checks"

echo "[static-checks] Checking recording scripts and docs"
test -f "${REPO_ROOT}/3-recording_scripts/video.sh"
test -f "${REPO_ROOT}/3-recording_scripts/photos.sh"
grep -q 'ANTCAM_RECORDING_FPS' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'ANTCAM_FPS_VALUE_FILE' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'ANTCAM_RECORDING_LENGTH' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'ANTCAM_LENGTH_VALUE_FILE' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'ANTCAM_RECORDING_SEGMENT' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'ANTCAM_SEGMENT_VALUE_FILE' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'ANTCAM_RECORDING_LOOP' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'ANTCAM_LOOP_VALUE_FILE' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'ANTCAM_UPLOAD_DIR' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'resolve_upload_dir_path' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'resolve_session_hostname' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q '%Y-%m-%d_%H-%M-%S' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'session_dir=' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'video-%05d.h264' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'set length <duration>' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'set segment <duration>' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'set loop <duration|none|0>' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'set fps <value>' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'framerate \"\\${fps_value}\"' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'duration_to_milliseconds' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'timeout \"\\${clip_timeout_ms}\"' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'segment <= loop' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'clips start immediately after each clip' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'start_epoch_ms' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'target_epoch_ms' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'Focus mode: auto' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'set focus <lens-position|auto>' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'lens-position' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'ANTCAM_FOCUS_VALUE_FILE' "${REPO_ROOT}/3-recording_scripts/video.sh"
grep -q 'ANTCAM_RECORDING_LENGTH' "${REPO_ROOT}/3-recording_scripts/photos.sh"
grep -q 'ANTCAM_LENGTH_VALUE_FILE' "${REPO_ROOT}/3-recording_scripts/photos.sh"
grep -q 'ANTCAM_RECORDING_LOOP' "${REPO_ROOT}/3-recording_scripts/photos.sh"
grep -q 'ANTCAM_LOOP_VALUE_FILE' "${REPO_ROOT}/3-recording_scripts/photos.sh"
grep -q 'ANTCAM_UPLOAD_DIR' "${REPO_ROOT}/3-recording_scripts/photos.sh"
grep -q 'resolve_upload_dir_path' "${REPO_ROOT}/3-recording_scripts/photos.sh"
grep -q 'resolve_session_hostname' "${REPO_ROOT}/3-recording_scripts/photos.sh"
grep -q '%Y-%m-%d_%H-%M-%S' "${REPO_ROOT}/3-recording_scripts/photos.sh"
grep -q 'session_dir=' "${REPO_ROOT}/3-recording_scripts/photos.sh"
grep -q 'photos-%05d.jpg' "${REPO_ROOT}/3-recording_scripts/photos.sh"
grep -q 'set length <duration>' "${REPO_ROOT}/3-recording_scripts/photos.sh"
grep -q 'set loop <duration|none|0>' "${REPO_ROOT}/3-recording_scripts/photos.sh"
grep -q 'loop >= 10s' "${REPO_ROOT}/3-recording_scripts/photos.sh"
grep -q 'one photo per run' "${REPO_ROOT}/3-recording_scripts/photos.sh"
grep -q 'start_epoch_ms' "${REPO_ROOT}/3-recording_scripts/photos.sh"
grep -q 'target_epoch_ms' "${REPO_ROOT}/3-recording_scripts/photos.sh"
grep -q -- '--immediate' "${REPO_ROOT}/3-recording_scripts/photos.sh"
grep -q 'Focus mode: auto' "${REPO_ROOT}/3-recording_scripts/photos.sh"
grep -q 'set focus <lens-position|auto>' "${REPO_ROOT}/3-recording_scripts/photos.sh"
grep -q 'lens-position' "${REPO_ROOT}/3-recording_scripts/photos.sh"
grep -q 'ANTCAM_FOCUS_VALUE_FILE' "${REPO_ROOT}/3-recording_scripts/photos.sh"
test -f "${REPO_ROOT}/3-recording_scripts/README.md"
grep -q 'recording_start' "${REPO_ROOT}/3-recording_scripts/README.md"
grep -q 'recording_end' "${REPO_ROOT}/3-recording_scripts/README.md"
grep -q 'diagnostics/recordings' "${REPO_ROOT}/3-recording_scripts/README.md"
grep -q 'antcam start <recording-script-name>' "${REPO_ROOT}/3-recording_scripts/README.md"
grep -q 'antcam focus check' "${REPO_ROOT}/3-recording_scripts/README.md"
grep -q 'antcam focus set <lens-position|auto>' "${REPO_ROOT}/3-recording_scripts/README.md"
grep -q 'antcam fps set <value>' "${REPO_ROOT}/3-recording_scripts/README.md"
grep -q 'antcam length set <duration>' "${REPO_ROOT}/3-recording_scripts/README.md"
grep -q 'antcam segment set <duration>' "${REPO_ROOT}/3-recording_scripts/README.md"
grep -q 'antcam loop set <duration|none|0>' "${REPO_ROOT}/3-recording_scripts/README.md"
grep -q 'antcam fps report' "${REPO_ROOT}/3-recording_scripts/README.md"
grep -q 'antcam length report' "${REPO_ROOT}/3-recording_scripts/README.md"
grep -q 'antcam segment report' "${REPO_ROOT}/3-recording_scripts/README.md"
grep -q 'antcam loop report' "${REPO_ROOT}/3-recording_scripts/README.md"
grep -q 'antcam stop' "${REPO_ROOT}/3-recording_scripts/README.md"
grep -q 'antcam_focus_autofocus.sh' "${REPO_ROOT}/3-recording_scripts/README.md"
grep -q 'video.sh' "${REPO_ROOT}/3-recording_scripts/README.md"
grep -q 'photos.sh' "${REPO_ROOT}/3-recording_scripts/README.md"
grep -q 'recording-active-state.env' "${REPO_ROOT}/3-recording_scripts/README.md"
grep -q 'YYYY-MM-DD_HH-MM-SS__hostname' "${REPO_ROOT}/3-recording_scripts/README.md"
grep -q 'lens-position' "${REPO_ROOT}/3-recording_scripts/README.md"
grep -q 'focus-result-lens-position-' "${REPO_ROOT}/3-recording_scripts/README.md"
grep -q '__T-HH-MM-SS__' "${REPO_ROOT}/3-recording_scripts/README.md"
echo "[static-checks] OK recording scripts/docs"

echo "[static-checks] Checking upload docs for store-and-forward behavior"
grep -q 'store-and-forward' "${REPO_ROOT}/4-upload/README.md"
grep -q 'queue.db' "${REPO_ROOT}/4-upload/README.md"
grep -q 'rclone copyto' "${REPO_ROOT}/4-upload/README.md"
grep -q 'protect' "${REPO_ROOT}/4-upload/README.md"
grep -q 'rolling' "${REPO_ROOT}/4-upload/README.md"
test -f "${REPO_ROOT}/4-upload/UPLOAD_WORKER_REWRITE_PLAN.md"
grep -q 'spool-and-ship' "${REPO_ROOT}/4-upload/UPLOAD_WORKER_REWRITE_PLAN.md"
echo "[static-checks] OK upload docs checks"

echo "[static-checks] Checking upload worker safety features"
grep -q 'CREATE TABLE IF NOT EXISTS artifacts' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'CREATE TABLE IF NOT EXISTS artifact_targets' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'CREATE TABLE IF NOT EXISTS attempt_log' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'make_file_identity' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'resolve_upload_dir' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'resolve_upload_config_dir' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'is_still_image' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'MIN_FILE_AGE_STILL_IMAGE' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'MIN_FILE_AGE_STATE_AND_LOG' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'is_slow_maturity_file' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'FILE_STABILITY_CHECK_INTERVAL_STILL_IMAGE' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'emit_upload_event' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'UPLOAD_EVENT status=' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'fleet/report/{DEVICE_ID}' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'publish_with_fleet_publish' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'publish_with_mqtt_report_cli' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'encrypt=True' "${REPO_ROOT}/4-upload/upload_worker.sh"
! grep -q -- '--no-encrypt' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'rclone copyto' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'ship_to_local_target' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'CURRENT_UPLOAD_PROFILE' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'CURRENT_UPLOAD_RETENTION' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'request_protect_stop_if_needed' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'prune_oldest_shipped_until_low_watermark' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'upload_queued' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'upload_shipped' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'upload_retry_scheduled' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q -- '--immutable' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'build_conflict_relative_path' "${REPO_ROOT}/4-upload/upload_worker.sh"
grep -q 'MACHINE_SUFFIX' "${REPO_ROOT}/4-upload/upload_worker.sh"
echo "[static-checks] OK upload worker checks"

echo "[static-checks] Checking install defaults"
grep -q 'Environment="RCLONE_REMOTE=gdrive_personal"' "${REPO_ROOT}/install.sh"
grep -q 'Environment="RCLONE_PATH="' "${REPO_ROOT}/install.sh"
grep -q 'Environment="UPLOAD_DIR=${upload_dir}"' "${REPO_ROOT}/install.sh"
grep -q 'Environment="UPLOAD_CONFIG_DIR=${upload_config_dir}"' "${REPO_ROOT}/install.sh"
grep -q 'Environment="UPLOAD_PROFILE=field"' "${REPO_ROOT}/install.sh"
grep -q 'Environment="UPLOAD_RETENTION=protect"' "${REPO_ROOT}/install.sh"
grep -q 'Environment="UPLOAD_HIGH_WATERMARK_PERCENT=80"' "${REPO_ROOT}/install.sh"
grep -q 'Environment="UPLOAD_LOW_WATERMARK_PERCENT=70"' "${REPO_ROOT}/install.sh"
grep -q 'disable_dynamic_camera_service' "${REPO_ROOT}/install.sh"
grep -q 'install_camera_cli' "${REPO_ROOT}/install.sh"
grep -q 'sudo antcam apply imx708' "${REPO_ROOT}/install.sh"
grep -q 'sudo antcam cam report' "${REPO_ROOT}/install.sh"
grep -q 'antcam focus set 7.5' "${REPO_ROOT}/install.sh"
grep -q 'antcam focus set auto' "${REPO_ROOT}/install.sh"
grep -q 'antcam fps set 1' "${REPO_ROOT}/install.sh"
grep -q 'antcam length set 30h' "${REPO_ROOT}/install.sh"
grep -q 'antcam segment set 10m' "${REPO_ROOT}/install.sh"
grep -q 'antcam loop set 1m' "${REPO_ROOT}/install.sh"
grep -q 'antcam focus report' "${REPO_ROOT}/install.sh"
grep -q 'antcam fps report' "${REPO_ROOT}/install.sh"
grep -q 'antcam length report' "${REPO_ROOT}/install.sh"
grep -q 'antcam segment report' "${REPO_ROOT}/install.sh"
grep -q 'antcam loop report' "${REPO_ROOT}/install.sh"
grep -q 'antcam start video' "${REPO_ROOT}/install.sh"
grep -q 'antcam start photos' "${REPO_ROOT}/install.sh"
grep -q 'antcam stop' "${REPO_ROOT}/install.sh"
grep -q 'antcam focus check' "${REPO_ROOT}/install.sh"
grep -q 'antcam upload set profile field' "${REPO_ROOT}/install.sh"
grep -q 'antcam upload set retention protect' "${REPO_ROOT}/install.sh"
grep -q 'antcam upload report queue' "${REPO_ROOT}/install.sh"
grep -q 'antcam upload prune --older-than 72h --dry-run' "${REPO_ROOT}/install.sh"
grep -q 'FOCUS_SCRIPT_SOURCE' "${REPO_ROOT}/install.sh"
grep -q 'FOCUS_SCRIPT_TARGET' "${REPO_ROOT}/install.sh"
grep -q 'RECORDING_SCRIPT_SOURCE_DIR' "${REPO_ROOT}/install.sh"
grep -q 'RECORDING_SCRIPT_TARGET_DIR' "${REPO_ROOT}/install.sh"
grep -q 'MQTT_EVENT_ENABLED' "${REPO_ROOT}/install.sh"
grep -q 'MQTT_REPORT_BIN' "${REPO_ROOT}/install.sh"
grep -q 'FLEET_EVENT_TOPIC_TEMPLATE' "${REPO_ROOT}/install.sh"
echo "[static-checks] OK install defaults"

echo "[static-checks] All checks passed"
